using numl;
using numl.Supervised;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TitanicPredictionSolution
{
    /// <summary>
    /// The result of a DecisionTree prediction
    /// </summary>
    public class PredictionResult
    {
        /// <summary>
        /// The model generated by the learner
        /// </summary>
        //public LearningModel PredictionModel { get; set; }
        public IModel PredictionModel { get; set; }
        /// <summary>
        /// The data array used to generate the prediction
        /// </summary>
        public Passenger[] Passengers { get; set; }

    }
}
